twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
        contact_mail: '%env(CONTACT_MAIL)%'