vich_uploader:
    db_driver: orm

    mappings:
        cover:
            uri_prefix: '%app.path.item_cover_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.item_cover_images%'
            delete_on_remove: true
            delete_on_update: true
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'name' }