controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: ''
        fr: 'fr'
    requirements:
        _locale: '%app_locale%'
    defaults:
        _locale: '%locale%'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
